# Python Numpy Assignment 1

In [1]:
import numpy as np

#### 1: numpy.array():

Create a numpy array from an iterable

In [5]:
arr = np.array([1,3,4,5,6])
print(arr)
print("The type array is: ", type(arr))

[1 3 4 5 6]
The type array is:  <class 'numpy.ndarray'>


#### 2: Numpy.zeros()

Creates a numpy array with all elements equal to zero of given shape.

In [9]:
arr1 = np.zeros((2,3))
arr1

array([[0., 0., 0.],
       [0., 0., 0.]])

#### 3. numpy.ones()

Creates a numpy array with all elements equal to 1 of given shape.

In [11]:
arr2 = np.ones((2, 3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

#### 4. np.arange()

Create a evenley spaced array between the given numbers. To create an array from 1-9 with a step of 2:

In [13]:
arr3 = np.arange(1, 10, 2)
arr3

array([1, 3, 5, 7, 9])

#### 5. np.eye()

Create and Identity matrix of ``NxN`` shape.


In [15]:
arr4 = np.eye(4)
arr4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### 6. np.random.rand()

creates a array with a uniform distribution of numbers.


In [17]:
arr5 = np.random.rand(4,5)
arr5

array([[0.57112369, 0.1470083 , 0.10911121, 0.30836212, 0.56721414],
       [0.818144  , 0.92319061, 0.45784421, 0.79394982, 0.27798872],
       [0.3824222 , 0.06621563, 0.57642254, 0.85107545, 0.16592965],
       [0.94599573, 0.57861933, 0.05346785, 0.72950265, 0.76257375]])

 #### 7. np.random.radint(start , stop=None, size=None)
 
 create an array of random ints within start and stop with specified size.

In [19]:
arr6 = np.random.randint(1, 6, (2,4))
arr6

array([[4, 1, 2, 2],
       [5, 1, 1, 1]])

#### 8. np.reshape()

This method changes the shape of numpy array

In [24]:
arr7 = np.arange(0,24)
print("Array before reshaping: ", arr7)
arr7 = arr7.reshape(2,3,4)
print("Array after reshaping: \n", arr7)

Array before reshaping:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Array after reshaping: 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


#### 9. np.astype()

This method is used to change the datatype of numpy array.

In [28]:
arr8 = np.ones((2,3))
print("The data type of array elements: ", arr8.dtype)
arr8 = arr8.astype(np.int8)
print("The data type of array elements after change: ", arr8.dtype)

The data type of array elements:  float64
The data type of array elements after change:  int8


#### 10. np.max()

Returns the maximum values from the array


In [35]:
arr9 = np.random.rand(3,3)
print("The array is: \n", arr9)
max_val = arr9.max()
print("The max value is: ", max_val)

The array is: 
 [[0.6730738  0.20107914 0.12956805]
 [0.62352135 0.08606899 0.52765925]
 [0.82398084 0.04831674 0.26197621]]
The max value is:  0.8239808436258509


#### 10. np.min()

Returns the minimum value from array.

In [36]:
max_val = arr9.min()
print("The max value is: ", max_val)

The max value is:  0.048316735720863035


#### 11. np.resize()

The method is used to chnage the size of numpy array.The missing elements are assigned a value of zero


In [41]:
arr10 = np.array([[1,2,3,4], 
                  [3,4,5,6,]])
arr10.resize((4,6))

print("Array after resize: ")
print(arr10)

Array after resize: 
[[1 2 3 4 3 4]
 [5 6 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


#### 12. np.sqrt()

This method return a array with square root of all elements.



In [43]:
arr11 = np.arange(8).reshape(4,2)
arr11

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [45]:
print("Square roots are: \n", np.sqrt(arr11))

Square roots are: 
 [[0.         1.        ]
 [1.41421356 1.73205081]
 [2.         2.23606798]
 [2.44948974 2.64575131]]


#### 13. np.cbrt()

returns an array with cube root of array.

In [47]:
print("Cube roots are: \n", np.cbrt(arr11))

Cube roots are: 
 [[0.         1.        ]
 [1.25992105 1.44224957]
 [1.58740105 1.70997595]
 [1.81712059 1.91293118]]


#### 14. np.square()

Returns square of the numpy array

In [49]:
print("The array with squared elements are: \n", np.square(arr11))

The array with squared elements are: 
 [[ 0  1]
 [ 4  9]
 [16 25]
 [36 49]]


#### 15. np.amax()

Returns max value from specified axis.

In [53]:
arr12 = np.random.randint(2,10,(4,4))
arr12

array([[7, 9, 2, 2],
       [6, 4, 8, 4],
       [5, 5, 6, 5],
       [2, 9, 7, 4]])

In [58]:
np.amax(arr12,1)

array([9, 8, 6, 9])

#### 16. np.amin()

Reutrns a min value from a specified axis.

In [59]:
np.amin(arr12, 0)

array([2, 4, 2, 2])

#### 17. np.cumsum

Returns the cumulative sum of array

In [60]:
np.cumsum(arr12)

array([ 7, 16, 18, 20, 26, 30, 38, 42, 47, 52, 58, 63, 65, 74, 81, 85],
      dtype=int32)

#### 18. np.divide(x1,x2)

Divide x1 array with x2 elemnent wise.


In [61]:
arr14 = np.random.randint(2,10,(4,4))
arr14

array([[3, 4, 4, 5],
       [6, 5, 8, 8],
       [9, 2, 6, 9],
       [4, 7, 2, 7]])

In [62]:
arr15 = np.random.randint(2,10,(4,4))
arr15

array([[7, 6, 2, 9],
       [2, 6, 3, 7],
       [2, 6, 7, 5],
       [4, 9, 2, 4]])

In [63]:
np.divide(arr15, arr14)

array([[2.33333333, 1.5       , 0.5       , 1.8       ],
       [0.33333333, 1.2       , 0.375     , 0.875     ],
       [0.22222222, 3.        , 1.16666667, 0.55555556],
       [1.        , 1.28571429, 1.        , 0.57142857]])

#### 19. numpy.remainder()

devide the array elements and return mod element wise.

In [65]:
np.remainder(arr15, arr14)

array([[1, 2, 2, 4],
       [2, 1, 3, 7],
       [2, 0, 1, 5],
       [0, 2, 0, 4]], dtype=int32)

### Comparisons


#### 20. np.greater(x1, x2)

compare two arrays element wise,and return the True/False depending on comparison ``x1 > x2``

In [66]:
np.greater(arr14, arr15)

array([[False, False,  True, False],
       [ True, False,  True,  True],
       [ True, False, False,  True],
       [False, False, False,  True]])

#### 21. np.less(x1, x2)

compare two arrays element wise,and return the True/False depending on comparison ``x1 < x2``

In [67]:
np.less(arr14, arr15)

array([[ True,  True, False,  True],
       [False,  True, False, False],
       [False,  True,  True, False],
       [False,  True, False, False]])

#### 22. np.equal(x1, x2)

compare two arrays element wise,and return the True/False depending on comparison ``x1 == x2``

In [69]:
np.equal(arr14, arr15)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False,  True, False]])

#### 23. np.not_equal(x1, x2)

compare two arrays element wise,and return the True/False depending on comparison ``x1 != x2``

In [70]:
np.not_equal(arr14, arr15)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False,  True, False,  True]])

#### 24. np.greater_equal(x1, x2)

compare two arrays element wise,and return the True/False depending on comparison x1 >= x2

In [71]:
np.greater_equal(arr14, arr15)

array([[False, False,  True, False],
       [ True, False,  True,  True],
       [ True, False, False,  True],
       [ True, False,  True,  True]])

#### 25. np.less_equal(x1, x2)

compare two arrays element wise,and return the True/False depending on comparison ``x1 <= x2``

In [72]:
np.less_equal(arr14, arr15)

array([[ True,  True, False,  True],
       [False,  True, False, False],
       [False,  True,  True, False],
       [ True,  True,  True, False]])

### Logical Operation

In [73]:
arr16 = np.array([True, False, True, True])
arr16

array([ True, False,  True,  True])

In [74]:
arr17 = np.array([False, False, True, False])
arr17

array([False, False,  True, False])

#### 26. np.logical_and(x1, x2)

Return an array based on ``x1 and x2`` 

In [75]:
np.logical_and(arr16, arr17)

array([False, False,  True, False])

#### 27. np.logical_or(x1, x2)
Return an array based on ``x1 or x2``

In [76]:
np.logical_or(arr16, arr17)

array([ True, False,  True,  True])

#### 28. np.logical_not(x1, x2)

Return an array based on ``x1 not x2``

In [77]:
np.logical_not(arr16)

array([False,  True, False, False])

#### 29. np.logical_xor(x1, x2)

Return an array based on ``x1 xor x2``

In [79]:
np.logical_xor(arr16, arr17)

array([ True, False, False,  True])

#### 30. np.power(x1, x2)

returns an array with x1 raised to power x2 element wise.

In [81]:
arr18 = np.array([1,2,3,4,5])
arr19 = np.array([5,4,3,2,1])

np.power(arr18, arr19)

array([ 1, 16, 27, 16,  5], dtype=int32)

#### 31. np.rad2deg()

converts the angle from radian to degree.

In [84]:
arr20 = np.array([0, 1.507, 3.14])
np.rad2deg(arr20)

array([  0.        ,  86.34473973, 179.90874767])

#### 32. np.deg2rad()

Converts the angles from degree to radians.

In [85]:
arr21 = np.array([0, 90, 180])
np.deg2rad(arr21)

array([0.        , 1.57079633, 3.14159265])

#### 33. np.prod()

Returns the product of all element in array


In [86]:
arr22 = np.array([1,2,3,4])
arr22.prod()

24

#### 34. np.sum()

return the sum of all elements of array.

In [87]:
arr22.sum()

10

#### 35. np.average()

returns the average of array elements

In [88]:
np.average(arr22)

2.5

#### 36. np.sort()

sorts an array

In [89]:
arr22 = np.array([1,6,7,2,5,])

np.sort(arr22)

array([1, 2, 5, 6, 7])

#### 37. np.transpose()

take the transpose of numpy array

In [90]:
arr23 = np.array([
    [1,2,3,4],
    [5,6,7,8,],
    [9,10,11,12]])


In [91]:
arr23.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

#### 38. np.sin()

return the sin value of all elements.

In [95]:
arr24 = np.array([0, 1.57079633, 3.14159265])

In [96]:
np.sin(arr24)

array([0.00000000e+00, 1.00000000e+00, 3.58979303e-09])

#### 39. np.cos()

return the cos value of all elements

In [97]:
np.cos(arr24)

array([ 1.00000000e+00, -3.20510345e-09, -1.00000000e+00])

#### 40. np.tan()

returns the tan value of all elements

In [98]:
np.tan(arr24)

array([ 0.00000000e+00, -3.12002409e+08, -3.58979303e-09])

#### 41. np.searcsort()

returns the insertion index in a sorted array.

In [100]:
arr25 = np.array([2,5,3,58,4])

arr25.searchsorted(4)

3

#### 42. np.instersect1d()

returns the common elements from two arrays.

In [101]:
arr26 = np.array([3,5,3,2,7,6])
arr27 = np.array([8,5,2,2,4,8])

np.intersect1d(arr26, arr27)

array([2, 5])

#### 43. np.unique()

return the unique values from array.


In [103]:
arr28 = np.array([1,4,5,2,4,5,2])
np.unique(arr28)

array([1, 2, 4, 5])

#### 44. np.dot()

Return the dot product of two array.

In [106]:
arr29 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr30 = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(arr29,arr30)


array([[ 28.,  64.],
       [ 67., 181.]])

#### 45. np.multiply()

multiply two array elements wise.

In [107]:
arr31 = np.array([1,2,3,4,5])
arr32 = np.array([2,3,4,5,5])

np.multiply(arr31, arr32)

array([ 2,  6, 12, 20, 25])

#### 46. np.delete()

delete element from given index.

In [109]:
arr33 = np.array([1,2,3,4,5])
np.delete(arr33, 2)

array([1, 2, 4, 5])

#### 47. np.extract()

Return the elements of an array that satisfy some condition.

In [111]:
arr34 = np.array([2,3,4,5,6])
np.extract(arr34,arr34>3)

array([False, False,  True,  True,  True])

#### 48. np.split()

Split an array into multiple sub-arrays as views into ary.

In [114]:
arr35 = np.arange(15)
np.split(arr35, 3)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]

#### 49. np.shape

returns the shape of numpy array.

In [118]:
arr36 = np.arange(12).reshape(3,4)
arr36.shape

(3, 4)

#### 50. np.gcd(x1, x2)

return the greatest common divisor from two array.

In [119]:
arr37 = np.array([2,4,6,3,7,9])
arr38 = np.array([2,2,5,6,5,9])

np.gcd(arr37, arr38)

array([2, 2, 1, 3, 1, 9])